### ISSUE TITLE
点击tabbar切换时，tabIndex打印，发现执行了多次。

### ISSUE THREAD

**Issue by yaonuo** [everettjf/Yolo#3]
版本0.1.0
- (void)EVTTabPageScrollView:(EVTTabPageScrollView *)tabPageScrollView didPageItemSelected:(EVTTabPageScrollViewPageItem *)pageItem withTabIndex:(NSInteger)tabIndex

**Comment by everettjf** [comment]
收到。。但太古老了，不改了哈
