### ISSUE TITLE
hook static initializers的问题

### ISSUE THREAD

**Issue by crossyoureye** [everettjf/Yolo#5]
在 hook_cpp_init.mm 中也有 static 变量，这些变量不需要通过 __mod_init_func 来初始化吗？
`static std::vector<MemoryType> *g_initializer;`
`static int g_cur_index;`
`static MemoryType g_aslr;`

**Comment by everettjf** [comment]
仔细看，这几个类型，指针，整型，枚举。构造都不需要执行代码。因此就没必要产生。

________________________________
发件人: crossyoureye <notifications@github.com>
发送时间: Wednesday, October 23, 2019 5:27:12 PM
收件人: everettjf/Yolo <Yolo@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: [everettjf/Yolo] hook static initlizers的问题 (#5)


在 hook_cpp_init.mm 中也有 static 变量，这些变量不需要通过 __mod_init_func 来初始化吗？
static std::vector<MemoryType> *g_initializer; static int g_cur_index; static MemoryType g_aslr;

―
