### ISSUE TITLE
你好 有关hook方法

### ISSUE THREAD

**Issue by MoShenGuo** [everettjf/Yolo#6]
你好 有关获取方法执行时间,你这边是怎么思路的呢?你是直接hook 底层方法objc_msgSend 吗?如果hook这个方法的话,会是我们方法执行时间会比没有hook执行时间长,请问你是怎么解决的呢?谢谢

**Comment by everettjf** [comment]
执行时间肯定会长。
可以想办法尽量减少每次hook中执行的代码耗时。

**Comment by MoShenGuo** [comment]
你好 你有什么好的思路呢?我之前也是hook底层方法的,但是hook下来的速度是没有hook的速度慢了二倍左右,

**Comment by MoShenGuo** [comment]
你好 有关怎么去统计方法的执行时长,包括网络请求的时长,你那边有这些的处理吗?谢谢

**Comment by MoShenGuo** [comment]
<img width="740" alt="图片" src="https://user-images.githubusercontent.com/21171688/69216573-7c3c6c00-0ba7-11ea-87f2-3fd601f56b50.png">
你好  这个hook报错  怎么去解决它呢? 谢谢

**Comment by everettjf** [comment]
目前只支持arm64真机。
看下这里 https://github.com/everettjf/AppleTrace/wiki 和博客。
