### ISSUE TITLE
#define QWLoadable  有瑕疵

### ISSUE THREAD

**Issue by SummitXY** [everettjf/Yolo#7]
```
#define QWLoadable __attribute((used, section(QWLoadableSegmentName "," QWLoadableSectionName )))
```
替换后 __attribute里面：
`(used,section("__DATA" "," "QWLoadable"))`
感觉多了一个逗号，虽然也能过

**Comment by everettjf** [comment]
并没有多呀，展开是
("__DATA,QWLoadable")

**Comment by SummitXY** [comment]
emmm，QWLoadableSegmentName 被替换成 `"__DATA"`，QWLoadableSectionName被替换成`"QWLoadable"`，中间有个`","`，那么展开后成`"__DATA" "," "QWLoadable"`(说错了，是多了两个引号？

**Comment by everettjf** [comment]
仔细想想哈，没有错的哦😄

________________________________
